# docker-compose.yml

version: "3.3"

services:
  postgres:
    image: postgres:15.2-alpine
    volumes:
      - keycloak_postgres:/var/lib/postgresql/data
    ports:  
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: '${POSTGRES_DB}:-keycloak}'
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    volumes:
      - quarkus_keycloak:/opt/keycloak
    environment:
      DB_VENDOR: POSTGRES
      KC_PROXY: edge
      KC_HOSTNAME_ADMIN_URL: "${KC_HOSTNAME_URL:-http://localhost:8082}"
      KC_HOSTNAME_URL: "${KC_HOSTNAME_URL:-http://localhost:8082}"
      KC_HTTP_ENABLED: "${KC_HTTP_ENABLED:-true}"
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN:-admin}"
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-P@ssw0rd}
      DB_ADDR: postgres  // Set the address of the database to use for keycloak
      DB_DATABASE: '${POSTGRES_DB:-keycloak}'
      DB_USER: '${POSTGRES_USER:-postgres}'
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}
    ports:
      - ${KEYCLOAK_PORT:-8080}:8080
    depends_on:
      - postgres
    command: start

volumes:
  keycloak_postgres:
    driver: local
  quarkus_keycloak:
    driver: local